apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: random-pod-kill
spec:
  action: pod-kill
  mode: fixed
  value: '1'
  selector:
    namespaces: [production]
  duration: '10m'
  scheduler:
    cron: '@every 2h'
